#!/bin/bash

#############################################################################################
# POP-Java Archive Releaser
# Author : Clement Valentin (clementval)
# Creation date : 31/31/2011
# Description : This script is used to create a releasable archive of POP-Java version 
# -------------------------------------------------------------------------------------------
# IMPORTANT : Please, keep this log up to date 
#
# Update log
# Date         Author      Description
# 31/03/2011	clementval	First version of this script
#############################################################################################


################################################################
# Define the function to print the program usage
################################################################
usage()
{
cat << EOF

POP-Java releaser script v1.0

This program is used to create a releasable archive of POP-Java

Usage: create_release <version>
version should be in the form of 1.0
EOF
}

DDATE=$(date +%Y%m%d)
VERSION="1.0"
RELDIR="popjava_"$VERSION"_build_"$DDATE
ARCHIVE="$RELDIR.tar"

echo $RELDIR

#Create the temporary directory
mkdir $RELDIR

#copy needed item to temp dir
cp install $RELDIR
cp launch_testsuite $RELDIR
cp README $RELDIR
cp -R doc $RELDIR
cp -R etc $RELDIR
cp -R example $RELDIR
cp -R JarFile $RELDIR
cp -R javassist $RELDIR
cp -R plugin $RELDIR
cp -R popjava $RELDIR
cp -R popjavac $RELDIR
cp -R testsuite $RELDIR

#create the archive
tar -cf $ARCHIVE $RELDIR/*
gzip $ARCHIVE
rm -rf $RELDIR
