#!/bin/bash

if [ -z $POPJAVA_LOCATION ]
then
    POPJAVA_LOCATION=/usr/local/popj
fi

POPJAVA_JAR=$POPJAVA_LOCATION/JarFile/popjava.jar
POPJAVA_RUNNER=popjava.scripts.Popjrun

java -cp $POPJAVA_JAR $POPJAVA_RUNNER "$@"