/* Generated By:JavaCC: Do not edit this line. POPJParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface POPJParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 9;
  /** RegularExpression Id. */
  int FORMAL_COMMENT = 10;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 11;
  /** RegularExpression Id. */
  int ABSTRACT = 13;
  /** RegularExpression Id. */
  int ASSERT = 14;
  /** RegularExpression Id. */
  int ASYNC = 15;
  /** RegularExpression Id. */
  int BOOLEAN = 16;
  /** RegularExpression Id. */
  int BREAK = 17;
  /** RegularExpression Id. */
  int BYTE = 18;
  /** RegularExpression Id. */
  int CASE = 19;
  /** RegularExpression Id. */
  int CATCH = 20;
  /** RegularExpression Id. */
  int CHAR = 21;
  /** RegularExpression Id. */
  int CLASS = 22;
  /** RegularExpression Id. */
  int CONC = 23;
  /** RegularExpression Id. */
  int CONST = 24;
  /** RegularExpression Id. */
  int CONTINUE = 25;
  /** RegularExpression Id. */
  int _DEFAULT = 26;
  /** RegularExpression Id. */
  int DO = 27;
  /** RegularExpression Id. */
  int DOUBLE = 28;
  /** RegularExpression Id. */
  int ELSE = 29;
  /** RegularExpression Id. */
  int ENUM = 30;
  /** RegularExpression Id. */
  int EXTENDS = 31;
  /** RegularExpression Id. */
  int FALSE = 32;
  /** RegularExpression Id. */
  int FINAL = 33;
  /** RegularExpression Id. */
  int FINALLY = 34;
  /** RegularExpression Id. */
  int FLOAT = 35;
  /** RegularExpression Id. */
  int FOR = 36;
  /** RegularExpression Id. */
  int GOTO = 37;
  /** RegularExpression Id. */
  int IF = 38;
  /** RegularExpression Id. */
  int IMPLEMENTS = 39;
  /** RegularExpression Id. */
  int IMPORT = 40;
  /** RegularExpression Id. */
  int INSTANCEOF = 41;
  /** RegularExpression Id. */
  int INT = 42;
  /** RegularExpression Id. */
  int INTERFACE = 43;
  /** RegularExpression Id. */
  int LONG = 44;
  /** RegularExpression Id. */
  int MUTEX = 45;
  /** RegularExpression Id. */
  int NATIVE = 46;
  /** RegularExpression Id. */
  int NEW = 47;
  /** RegularExpression Id. */
  int NULL = 48;
  /** RegularExpression Id. */
  int OD = 49;
  /** RegularExpression Id. */
  int PACKAGE = 50;
  /** RegularExpression Id. */
  int PRIVATE = 51;
  /** RegularExpression Id. */
  int PARCLASS = 52;
  /** RegularExpression Id. */
  int PROTECTED = 53;
  /** RegularExpression Id. */
  int PUBLIC = 54;
  /** RegularExpression Id. */
  int RETURN = 55;
  /** RegularExpression Id. */
  int SEQ = 56;
  /** RegularExpression Id. */
  int SHORT = 57;
  /** RegularExpression Id. */
  int STATIC = 58;
  /** RegularExpression Id. */
  int STRICTFP = 59;
  /** RegularExpression Id. */
  int SUPER = 60;
  /** RegularExpression Id. */
  int SWITCH = 61;
  /** RegularExpression Id. */
  int SYNC = 62;
  /** RegularExpression Id. */
  int SYNCHRONIZED = 63;
  /** RegularExpression Id. */
  int THIS = 64;
  /** RegularExpression Id. */
  int THROW = 65;
  /** RegularExpression Id. */
  int THROWS = 66;
  /** RegularExpression Id. */
  int TRANSIENT = 67;
  /** RegularExpression Id. */
  int TRUE = 68;
  /** RegularExpression Id. */
  int TRY = 69;
  /** RegularExpression Id. */
  int VOID = 70;
  /** RegularExpression Id. */
  int VOLATILE = 71;
  /** RegularExpression Id. */
  int WHILE = 72;
  /** RegularExpression Id. */
  int ODURL = 73;
  /** RegularExpression Id. */
  int ODSEARCH = 74;
  /** RegularExpression Id. */
  int ODMANUAL = 75;
  /** RegularExpression Id. */
  int ODWALLTIME = 76;
  /** RegularExpression Id. */
  int ODPOWER = 77;
  /** RegularExpression Id. */
  int ODMEMORY = 78;
  /** RegularExpression Id. */
  int ODBANDWIDTH = 79;
  /** RegularExpression Id. */
  int ODDIRECTORY = 80;
  /** RegularExpression Id. */
  int ODJOBURL = 81;
  /** RegularExpression Id. */
  int ODEXECUTABLE = 82;
  /** RegularExpression Id. */
  int ODPROTOCOL = 83;
  /** RegularExpression Id. */
  int ODENCODING = 84;
  /** RegularExpression Id. */
  int ODRUNLOCAL = 85;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 86;
  /** RegularExpression Id. */
  int DECIMAL_LITERAL = 87;
  /** RegularExpression Id. */
  int HEX_LITERAL = 88;
  /** RegularExpression Id. */
  int OCTAL_LITERAL = 89;
  /** RegularExpression Id. */
  int FLOATING_POINT_LITERAL = 90;
  /** RegularExpression Id. */
  int EXPONENT = 91;
  /** RegularExpression Id. */
  int CHARACTER_LITERAL = 92;
  /** RegularExpression Id. */
  int STRING_LITERAL = 93;
  /** RegularExpression Id. */
  int IDENTIFIER = 94;
  /** RegularExpression Id. */
  int LETTER = 95;
  /** RegularExpression Id. */
  int DIGIT = 96;
  /** RegularExpression Id. */
  int LPAREN = 97;
  /** RegularExpression Id. */
  int RPAREN = 98;
  /** RegularExpression Id. */
  int LBRACE = 99;
  /** RegularExpression Id. */
  int RBRACE = 100;
  /** RegularExpression Id. */
  int LBRACKET = 101;
  /** RegularExpression Id. */
  int RBRACKET = 102;
  /** RegularExpression Id. */
  int SEMICOLON = 103;
  /** RegularExpression Id. */
  int COMMA = 104;
  /** RegularExpression Id. */
  int DOT = 105;
  /** RegularExpression Id. */
  int AT = 106;
  /** RegularExpression Id. */
  int ASSIGN = 107;
  /** RegularExpression Id. */
  int LT = 108;
  /** RegularExpression Id. */
  int BANG = 109;
  /** RegularExpression Id. */
  int TILDE = 110;
  /** RegularExpression Id. */
  int HOOK = 111;
  /** RegularExpression Id. */
  int COLON = 112;
  /** RegularExpression Id. */
  int EQ = 113;
  /** RegularExpression Id. */
  int LE = 114;
  /** RegularExpression Id. */
  int GE = 115;
  /** RegularExpression Id. */
  int NE = 116;
  /** RegularExpression Id. */
  int SC_OR = 117;
  /** RegularExpression Id. */
  int SC_AND = 118;
  /** RegularExpression Id. */
  int INCR = 119;
  /** RegularExpression Id. */
  int DECR = 120;
  /** RegularExpression Id. */
  int PLUS = 121;
  /** RegularExpression Id. */
  int MINUS = 122;
  /** RegularExpression Id. */
  int STAR = 123;
  /** RegularExpression Id. */
  int SLASH = 124;
  /** RegularExpression Id. */
  int BIT_AND = 125;
  /** RegularExpression Id. */
  int BIT_OR = 126;
  /** RegularExpression Id. */
  int XOR = 127;
  /** RegularExpression Id. */
  int REM = 128;
  /** RegularExpression Id. */
  int LSHIFT = 129;
  /** RegularExpression Id. */
  int PLUSASSIGN = 130;
  /** RegularExpression Id. */
  int MINUSASSIGN = 131;
  /** RegularExpression Id. */
  int STARASSIGN = 132;
  /** RegularExpression Id. */
  int SLASHASSIGN = 133;
  /** RegularExpression Id. */
  int ANDASSIGN = 134;
  /** RegularExpression Id. */
  int ORASSIGN = 135;
  /** RegularExpression Id. */
  int XORASSIGN = 136;
  /** RegularExpression Id. */
  int REMASSIGN = 137;
  /** RegularExpression Id. */
  int LSHIFTASSIGN = 138;
  /** RegularExpression Id. */
  int RSIGNEDSHIFTASSIGN = 139;
  /** RegularExpression Id. */
  int RUNSIGNEDSHIFTASSIGN = 140;
  /** RegularExpression Id. */
  int ELLIPSIS = 141;
  /** RegularExpression Id. */
  int RUNSIGNEDSHIFT = 142;
  /** RegularExpression Id. */
  int RSIGNEDSHIFT = 143;
  /** RegularExpression Id. */
  int GT = 144;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_SINGLE_LINE_COMMENT = 1;
  /** Lexical state. */
  int IN_FORMAL_COMMENT = 2;
  /** Lexical state. */
  int IN_MULTI_LINE_COMMENT = 3;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"//\"",
    "<token of kind 7>",
    "\"/*\"",
    "<SINGLE_LINE_COMMENT>",
    "\"*/\"",
    "\"*/\"",
    "<token of kind 12>",
    "\"abstract\"",
    "\"assert\"",
    "\"async\"",
    "\"boolean\"",
    "\"break\"",
    "\"byte\"",
    "\"case\"",
    "\"catch\"",
    "\"char\"",
    "\"class\"",
    "\"conc\"",
    "\"const\"",
    "\"continue\"",
    "\"default\"",
    "\"do\"",
    "\"double\"",
    "\"else\"",
    "\"enum\"",
    "\"extends\"",
    "\"false\"",
    "\"final\"",
    "\"finally\"",
    "\"float\"",
    "\"for\"",
    "\"goto\"",
    "\"if\"",
    "\"implements\"",
    "\"import\"",
    "\"instanceof\"",
    "\"int\"",
    "\"interface\"",
    "\"long\"",
    "\"mutex\"",
    "\"native\"",
    "\"new\"",
    "\"null\"",
    "\"od\"",
    "\"package\"",
    "\"private\"",
    "\"parclass\"",
    "\"protected\"",
    "\"public\"",
    "\"return\"",
    "\"seq\"",
    "\"short\"",
    "\"static\"",
    "\"strictfp\"",
    "\"super\"",
    "\"switch\"",
    "\"sync\"",
    "\"synchronized\"",
    "\"this\"",
    "\"throw\"",
    "\"throws\"",
    "\"transient\"",
    "\"true\"",
    "\"try\"",
    "\"void\"",
    "\"volatile\"",
    "\"while\"",
    "\"url\"",
    "\"search\"",
    "\"manual\"",
    "\"walltime\"",
    "\"power\"",
    "\"memory\"",
    "\"bandwidth\"",
    "\"directory\"",
    "\"joburl\"",
    "\"executable\"",
    "\"protocol\"",
    "\"encoding\"",
    "\"runLocal\"",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<EXPONENT>",
    "<CHARACTER_LITERAL>",
    "<STRING_LITERAL>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"@\"",
    "\"=\"",
    "\"<\"",
    "\"!\"",
    "\"~\"",
    "\"?\"",
    "\":\"",
    "\"==\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"||\"",
    "\"&&\"",
    "\"++\"",
    "\"--\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&\"",
    "\"|\"",
    "\"^\"",
    "\"%\"",
    "\"<<\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "\"&=\"",
    "\"|=\"",
    "\"^=\"",
    "\"%=\"",
    "\"<<=\"",
    "\">>=\"",
    "\">>>=\"",
    "\"...\"",
    "\">>>\"",
    "\">>\"",
    "\">\"",
  };

}
